ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE ARTICLE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE ARTICLECOMPL CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE ARTICLETIERS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE CHOIXCOD CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE CHOIXEXT CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE COMMERCIAL CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE COMMUN CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE DEPOTS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE DIMENSION CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE DISPO CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE DISPOSERIE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE ETABLISS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE LIGNE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE LIGNESERIE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE LINE_STATUS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE MARTICLETAB CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE METABDEPOT CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE MPOIDSNUMSERIE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE MTARIFCALC CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE OPERCAISSE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE PARCAISSE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE PIECE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE PRINTING_QUEUE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE QUICKTRANSFER CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE REQUESTED_QUANTITY_BY_ARTICLE_FOR_CC CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE RESTRICTETAB CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE STATUS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE STKFICHETRACE CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE TIERS CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE TRADDATA CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE UTILISAT CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE UTILISATCOMPL CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE YPRFCULTUREL CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE YYLANGISO CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE YYLANGPAYSISO CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE ZHERMES CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE application_minimum_version CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE expiration_date CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE partitioned_exports CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE stock_groupe CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE stock_print_template CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE stock_store_printer CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE store_zone CONVERT TO CHARACTER SET utf8mb4;