ALTER DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE application_minimum_version (
  minimum_version nvarchar(100) NOT NULL,
  link_update nvarchar(256) DEFAULT NULL,
  subsidiary_id nvarchar(6) NOT NULL,
  application_name nvarchar(100) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (application_name,subsidiary_id,ZONE)
);

CREATE TABLE ARTICLE (
  GA_ARTICLE nvarchar(35) NOT NULL,
  GA_CODEARTICLE nvarchar(18) NOT NULL,
  GA_CODEBARRE nvarchar(18) NOT NULL,
  GA_LIBELLE nvarchar(70) NOT NULL,
  GA_FAMILLENIV1 nchar(3) NOT NULL,
  GA_FAMILLENIV2 nchar(3) DEFAULT NULL,
  GA_FAMILLENIV3 nchar(3) NOT NULL,
  GA_NUMEROSERIE tinyint(1) NOT NULL,
  GA_TYPEARTICLE nchar(3) NOT NULL,
  GA_TENUESTOCK tinyint(1) NOT NULL DEFAULT '1',
  GA_DESIGNATION1 nvarchar(100) DEFAULT NULL,
  GA_LIBREART3 nvarchar(6) DEFAULT NULL,
  GA_LIBREART5 nvarchar(6) DEFAULT NULL,
  GA_LIBREART6 nvarchar(6) DEFAULT NULL,
  GA_LIBREART7 nvarchar(6) DEFAULT NULL,
  GA_GRILLEDIM1 nchar(3) DEFAULT NULL,
  GA_CODEDIM1 nchar(3) DEFAULT NULL,
  GA_CODEDIM2 nchar(3) DEFAULT NULL,
  GA_GRILLEDIM2 nchar(3) DEFAULT NULL,
  GA_STATUTART nchar(3) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GA_ARTICLE,ZONE),
  KEY ga_codebarre_and_zone (GA_CODEBARRE,ZONE)
);

CREATE TABLE ARTICLECOMPL (
  GA2_ARTICLE nvarchar(35) NOT NULL,
  GA2_BOOLLIBREE tinyint(1) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GA2_ARTICLE,ZONE)
);

CREATE TABLE ARTICLETIERS (
  GAT_ARTICLE nvarchar(35) NOT NULL,
  GAT_REFARTICLE nvarchar(35) NOT NULL,
  GAT_TYPREFARTTIERS nchar(3) NOT NULL,
  GAT_REFTIERS nvarchar(17) NOT NULL,
  GAT_INDICE int(10) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GAT_ARTICLE,GAT_TYPREFARTTIERS,GAT_REFTIERS,GAT_INDICE,ZONE),
  KEY gat_refarticle (GAT_REFARTICLE)
);

CREATE TABLE CHOIXCOD (
  CC_TYPE nchar(3) NOT NULL,
  CC_CODE nchar(3) NOT NULL,
  CC_LIBELLE nvarchar(105) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (CC_CODE,CC_TYPE,ZONE)
);

CREATE TABLE CHOIXEXT (
  YX_ABREGE nvarchar(105) DEFAULT NULL,
  YX_LIBELLE nvarchar(105) DEFAULT NULL,
  YX_CODE nvarchar(17) NOT NULL,
  YX_TYPE nchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (YX_CODE,YX_TYPE,ZONE)
);

CREATE TABLE COMMERCIAL (
  GCL_COMMERCIAL nvarchar(17) NOT NULL,
  GCL_LIBELLE nvarchar(35) DEFAULT NULL,
  GCL_UTILASSOCIE nchar(3) DEFAULT NULL,
  GCL_ETABLISSEMENT nvarchar(6) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GCL_COMMERCIAL,ZONE),
  KEY user_commercial (GCL_UTILASSOCIE,GCL_ETABLISSEMENT,ZONE)
);

CREATE TABLE COMMUN (
  CO_LIBELLE nvarchar(105) DEFAULT NULL,
  CO_CODE nchar(3) NOT NULL,
  CO_TYPE nchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (CO_CODE,CO_TYPE,ZONE)
);

CREATE TABLE DEPOTS (
  GDE_DEPOT nvarchar(6) NOT NULL,
  GDE_LIBELLE nvarchar(35) NOT NULL,
  GDE_TYPEDEPOT nchar(3) DEFAULT NULL,
  GDE_LIBREDEP8 nvarchar(6) DEFAULT NULL,
  GDE_NUMEROSERIE tinyint(1) DEFAULT NULL,
  GDE_WMS tinyint(1) DEFAULT NULL,
  GDE_DEPOTDEPORTE tinyint(1) NOT NULL,
  GDE_FERME tinyint(1) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GDE_DEPOT,ZONE)
);

CREATE TABLE DIMENSION (
  GDI_LIBELLE nvarchar(35) DEFAULT NULL,
  GDI_TYPEDIM nchar(3) NOT NULL,
  GDI_GRILLEDIM nchar(3) NOT NULL,
  GDI_CODEDIM nchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GDI_TYPEDIM,GDI_GRILLEDIM,GDI_CODEDIM,ZONE)
);

CREATE TABLE DISPO (
  GQ_PHYSIQUE int(11) DEFAULT NULL,
  GQ_PREPACLI int(11) DEFAULT NULL,
  GQ_DISPOCLI int(11) DEFAULT NULL,
  GQ_RESERVECLI int(11) DEFAULT NULL,
  GQ_PANIERWEB int(11) DEFAULT NULL,
  GQ_BROUILLONBEX int(11) DEFAULT NULL,
  GQ_BROUILLONBRF int(11) DEFAULT NULL,
  GQ_BROUILLONBSX int(11) DEFAULT NULL,
  GQ_BROUILLONTRF int(11) DEFAULT NULL,
  GQ_ARTICLE nvarchar(35) NOT NULL,
  GQ_DEPOT nvarchar(6) NOT NULL,
  GQ_CLOTURE tinyint(1) NOT NULL,
  GQ_DATECLOTURE datetime NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GQ_ARTICLE,GQ_DEPOT,GQ_CLOTURE,GQ_DATECLOTURE,ZONE)
);

CREATE TABLE DISPOSERIE (
  GQS_IDSERIE nvarchar(35) NOT NULL,
  GQS_ARTICLE nvarchar(35) NOT NULL,
  GQS_DEPOT nvarchar(6) NOT NULL,
  GQS_ENSTOCK tinyint(1) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GQS_IDSERIE,GQS_ARTICLE,GQS_DEPOT,ZONE)
);

CREATE TABLE ETABLISS (
  ET_ETABLISSEMENT nvarchar(6) NOT NULL,
  ET_LIBELLE nvarchar(35) DEFAULT NULL,
  ET_LIBREETA nvarchar(6) DEFAULT NULL,
  ET_LIBREET1 nvarchar(6) DEFAULT NULL,
  ET_LIBREET2 nvarchar(6) DEFAULT NULL,
  ET_LIBREET6 nvarchar(6) DEFAULT NULL,
  ET_NUMEROSERIE tinyint(1) DEFAULT NULL,
  ET_CHARLIBRE3 nvarchar(6) DEFAULT NULL,
  ET_FILIALE nchar(3) DEFAULT NULL,
  ET_PAYS nchar(3) DEFAULT NULL,
  ET_DEVISE nchar(3) DEFAULT NULL,
  ET_FERME nchar(1) DEFAULT NULL,
  ET_SUPPRIME nchar(1) DEFAULT NULL,
  ET_TYPETARIFVTETTC nvarchar(6) DEFAULT NULL,
  ET_TYPETARIFVTEHT nvarchar(6) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (ET_ETABLISSEMENT,ZONE)
);

CREATE TABLE expiration_date (
  subsidiary_id nvarchar(6) NOT NULL,
  days_before_expiration int(10) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (subsidiary_id, ZONE),
  KEY expiration_date_id (subsidiary_id)
);

CREATE TABLE LIGNE (
  GL_NATUREPIECEG nchar(3) NOT NULL,
  GL_SOUCHE nvarchar(6) NOT NULL,
  GL_INDICEG int(10) NOT NULL,
  GL_ARTICLE nvarchar(35) DEFAULT NULL,
  GL_NUMLIGNE int(10) NOT NULL,
  GL_DEPOT nvarchar(6) DEFAULT NULL,
  GL_TIERS nvarchar(17) DEFAULT NULL,
  GL_NUMERO int(10) NOT NULL,
  GL_NUMORDRE int(10) DEFAULT NULL,
  GL_DATEPIECE datetime DEFAULT NULL,
  GL_DATEEXPIRATION datetime DEFAULT NULL,
  GL_QTERESTE decimal(10,0) DEFAULT NULL,
  GL_REPRESENTANT nvarchar(17) DEFAULT NULL,
  GL_VIVANTE tinyint(1) NOT NULL,
  GL_TYPELIGNE nchar(3) DEFAULT NULL,
  GL_DEVISE nchar(3) NOT NULL,
  GL_PUHTDEV decimal(18,4) DEFAULT NULL,
  GL_QTEFACT decimal(18,4) DEFAULT NULL,
  GL_REFCOLIS nvarchar(35) DEFAULT NULL,
  GL_REFARTBARRE nvarchar(18) DEFAULT NULL,
  GL_PUTTCDEV decimal(18,4) DEFAULT NULL,
  GL_PUHTNETDEV decimal(18,4) DEFAULT NULL,
  GL_LIBELLE nvarchar(70) DEFAULT NULL,
  GL_TOTALTTCDEV decimal(18,4) DEFAULT NULL,
  GL_PIECEORIGINE nvarchar(40) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GL_NATUREPIECEG,GL_SOUCHE,GL_NUMERO,GL_INDICEG,GL_NUMLIGNE,ZONE)
);

CREATE TABLE LIGNESERIE (
  GLS_NATUREPIECEG nchar(3) NOT NULL,
  GLS_SOUCHE nvarchar(6) NOT NULL,
  GLS_NUMERO int(10) NOT NULL,
  GLS_INDICEG int(10) NOT NULL,
  GLS_ARTICLE nvarchar(35) NOT NULL,
  GLS_NUMLIGNE int(10) NOT NULL,
  GLS_IDSERIE nvarchar(35) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GLS_NATUREPIECEG,GLS_SOUCHE,GLS_NUMERO,GLS_INDICEG,GLS_NUMLIGNE,GLS_ARTICLE,GLS_IDSERIE,ZONE)
);

CREATE TABLE LINE_STATUS (
  LINE_NUMBER int(10) NOT NULL,
  LINE_INDICE int(10) NOT NULL,
  SOURCE_DOC_TYPE nchar(3) NOT NULL,
  SOURCE_DOC_NUMBER int(10) NOT NULL,
  STUB nvarchar(6) NOT NULL,
  STATUS enum('OK','WAITING') DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (LINE_NUMBER,LINE_INDICE,SOURCE_DOC_TYPE,SOURCE_DOC_NUMBER,STUB,ZONE)
);

CREATE TABLE MARTICLETAB (
  MAC_CONTENU1 nvarchar(200) DEFAULT NULL,
  MAC_ETABLISSEMENT nvarchar(6) NOT NULL,
  MAC_TYPELIEN nchar(3) NOT NULL,
  MAC_NUMERO int(10) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (MAC_ETABLISSEMENT,MAC_TYPELIEN,MAC_NUMERO,ZONE)
);

CREATE TABLE METABDEPOT (
  MDE_ETABLISSEMENT nvarchar(6) NOT NULL,
  MDE_PRIORITE int(10) NOT NULL,
  MDE_DEPOT nvarchar(6) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (MDE_ETABLISSEMENT,MDE_DEPOT,ZONE)
);

CREATE TABLE MPOIDSNUMSERIE (
  MNU_GUID nvarchar(36) NOT NULL,
  MNU_FERME tinyint(1) DEFAULT NULL,
  MNU_COMPOSANT nvarchar(17) NOT NULL,
  MNU_DATEMODIF datetime DEFAULT NULL,
  MNU_VALEUR decimal(18,4) DEFAULT NULL,
  MNU_MESURE nchar(3) DEFAULT NULL,
  MNU_DATEPESEE datetime NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (MNU_GUID,MNU_DATEPESEE,MNU_COMPOSANT,ZONE)
);

CREATE TABLE MTARIFCALC (
  MTC_ARTICLE nvarchar(35) NOT NULL,
  MTC_DEPOT nvarchar(6) NOT NULL,
  MTC_DATEAPPLIQUE datetime NOT NULL,
  MTC_PRIXCALCUL decimal(18,4) DEFAULT NULL,
  MTC_TARFMODE int(10) NOT NULL,
  MTC_TARIFSTATUT nchar(3) DEFAULT NULL,
  MTC_TYPETARIFDEST nvarchar(6) DEFAULT NULL,
  MTC_PROGRAMME nvarchar(3) NOT NULL,
  MTC_REGLE nvarchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (MTC_PROGRAMME,MTC_REGLE,MTC_ARTICLE,MTC_DEPOT,ZONE)
);

CREATE TABLE OPERCAISSE (
  GOC_TOTALDISPOTTC decimal(18,4) DEFAULT NULL,
  GOC_TIERS nvarchar(17) DEFAULT NULL,
  GOC_NATUREPIECEG nchar(3) NOT NULL,
  GOC_SOUCHE nvarchar(6) NOT NULL,
  GOC_NUMERO int(10) NOT NULL,
  GOC_TYPEARTFINAN nchar(3) DEFAULT NULL,
  GOC_PREFIXE nchar(3) NOT NULL,
  GOC_INDICEG int(10) NOT NULL,
  GOC_NUMLIGNE int(10) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GOC_NATUREPIECEG,GOC_SOUCHE,GOC_NUMERO,GOC_INDICEG,GOC_PREFIXE,GOC_NUMLIGNE,ZONE)
);

CREATE TABLE PARCAISSE (
  GPK_ETABLISSEMENT nvarchar(6) NOT NULL,
  GPK_APPELPRIXTIC nchar(3) DEFAULT NULL,
  GPK_TIERS nvarchar(17) NOT NULL,
  GPK_CAISSE nvarchar(6) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GPK_CAISSE,ZONE)
);

CREATE TABLE PIECE (
  GP_NATUREPIECEG nchar(3) NOT NULL,
  GP_DATEPIECE datetime DEFAULT NULL,
  GP_NUMERO int(10) NOT NULL,
  GP_REFEXTERNE nvarchar(40) DEFAULT NULL,
  GP_REFINTERNE nvarchar(40) DEFAULT NULL,
  GP_TIERS nvarchar(17) DEFAULT NULL,
  GP_DEPOT nvarchar(6) DEFAULT NULL,
  GP_ETABLISSDEST nvarchar(6) DEFAULT NULL,
  GP_ETABLISSEMENT nvarchar(6) NOT NULL,
  GP_VIVANTE tinyint(1) NOT NULL,
  GP_SUPPRIME tinyint(1) NOT NULL,
  GP_REFSUIVI nvarchar(40) DEFAULT NULL,
  GP_SOUCHE nvarchar(6) NOT NULL,
  GP_UTILISATEUR nchar(3) DEFAULT NULL,
  GP_DEPOTDEST nvarchar(6) DEFAULT NULL,
  GP_TOTALQTEFACT decimal(18,4) DEFAULT NULL,
  GP_TOTALHTDEV decimal(18,4) DEFAULT NULL,
  GP_TOTALTTCDEV decimal(18,4) DEFAULT NULL,
  GP_INDICEG int(10) NOT NULL,
  GP_DATEEXPIRATION date DEFAULT NULL,
  GP_TYPEPROVENANCE nvarchar(3) DEFAULT NULL,
  GP_HEURECREATION datetime DEFAULT NULL,
  GP_CREEPAR nchar(3) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GP_SOUCHE,GP_NATUREPIECEG,GP_NUMERO,GP_INDICEG,ZONE),
  KEY research_TRV (GP_ETABLISSDEST,GP_NATUREPIECEG,GP_NUMERO,GP_INDICEG,ZONE)
);

CREATE TABLE PRINTING_QUEUE (
  INTERNAL_REFERENCE nvarchar(40) NOT NULL,
  STORE_ID nvarchar(6) NOT NULL,
  USER_ID nvarchar(100) NOT NULL,
  LANGUAGE_ID nvarchar(100) NOT NULL,
  PRINTER_NAME nvarchar(100) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  COUNTRY_CODE nvarchar(100) DEFAULT NULL,
  PRINTING_TYPE enum('CDI_TAG','CDI_MAXI'),
  PRIMARY KEY (INTERNAL_REFERENCE,STORE_ID,ZONE)
);

CREATE TABLE QUICKTRANSFER (
  ID nvarchar(36) NOT NULL,
  OWNER_ID nvarchar(255) NOT NULL,
  STORE_ID nvarchar(6) NOT NULL,
  NAME nvarchar(256) NOT NULL,
  EMITTING_STOCKROOM_ID nvarchar(6) NOT NULL,
  RECIPIENT_STOCKROOM_ID nvarchar(6) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (OWNER_ID,EMITTING_STOCKROOM_ID,RECIPIENT_STOCKROOM_ID,ZONE)
);

CREATE TABLE REQUESTED_QUANTITY_BY_ARTICLE_FOR_CC (
  PRODUCT_REQUESTED_QUANTITY int(10) NOT NULL,
  CC_STUB nvarchar(6) NOT NULL,
  CC_NUMBER int(10) NOT NULL,
  PRODUCT_BARCODE nvarchar(35) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (CC_STUB,CC_NUMBER,PRODUCT_BARCODE,ZONE)
);

CREATE TABLE RESTRICTETAB (
  MRE_IDGRP nchar(3) NOT NULL,
  MRE_ETABLISREF nvarchar(255) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (MRE_IDGRP,ZONE)
);

CREATE TABLE STATUS (
  TYPE nvarchar(3) DEFAULT NULL,
  NUMBER int(11) DEFAULT NULL,
  SOURCE_DOC_TYPE nvarchar(3) DEFAULT NULL,
  SOURCE_DOC_NUMBER int(11) DEFAULT NULL,
  STUB nvarchar(6) DEFAULT NULL,
  USER_ID nvarchar(255) DEFAULT NULL,
  INTERNAL_REF nvarchar(40) DEFAULT NULL,
  STATUS enum('CREATION_REQUESTED','OK','TIME_OUT','ERROR') NOT NULL,
  CREATION_TIMESTAMP timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  TIMEOUT_TIMESTAMP timestamp NULL DEFAULT NULL,
  CREATION_STORE_ID nvarchar(6) NOT NULL,
  RECEIVING_STORE_ID nvarchar(6) DEFAULT NULL,
  EMITTING_STOCKROOM_ID nvarchar(6) DEFAULT NULL,
  RECEIVING_STOCKROOM_ID nvarchar(6) DEFAULT NULL,
  CDC_RETURN_TIMESTAMP timestamp NULL DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') DEFAULT NULL,
  KEY source_document_id (SOURCE_DOC_TYPE,SOURCE_DOC_NUMBER,STUB)
);

CREATE TABLE STKFICHETRACE (
  GST_GUID nvarchar(36) NOT NULL,
  GST_ARTICLE nvarchar(35) NOT NULL,
  GST_SERIEINTERNE nvarchar(35) NOT NULL,
  GST_TYPEGST nchar(6) NOT NULL,
  GST_LOTINTERNE nvarchar(35) NOT NULL,
  GST_SERIEEXTERNE nvarchar(35) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (GST_TYPEGST,GST_ARTICLE,GST_LOTINTERNE,GST_SERIEINTERNE,ZONE),
  KEY gst_article (GST_ARTICLE)
);

CREATE TABLE stock_groupe (
  code nchar(3) NOT NULL,
  label nvarchar(100) DEFAULT NULL,
  isAdmin tinyint(1) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (code,ZONE)
);

CREATE TABLE stock_print_template (
  print_type nvarchar(100) NOT NULL,
  template_name nvarchar(100) DEFAULT NULL,
  subsidiary_id nvarchar(6) DEFAULT NULL,
  format nvarchar(100) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (print_type,ZONE)
);

CREATE TABLE stock_store_printer (
  store_id nvarchar(6) NOT NULL,
  printer_name nvarchar(100) NOT NULL,
  type_id nvarchar(10) DEFAULT NULL,
  id nvarchar(118) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (id,ZONE)
);

CREATE TABLE store_zone (
  store_id nvarchar(6) NOT NULL,
  zone_id enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (store_id)
);

CREATE TABLE TIERS (
  T_TIERS nvarchar(17) NOT NULL,
  T_PRENOM nvarchar(35) DEFAULT NULL,
  T_LIBELLE nvarchar(35) DEFAULT NULL,
  T_JURIDIQUE nchar(3) NOT NULL,
  T_AUXILIAIRE nvarchar(17) DEFAULT NULL,
  T_NATUREAUXI nchar(3) NOT NULL,
  T_ADRESSE1 nvarchar(50) DEFAULT NULL,
  T_CODEPOSTAL nvarchar(10) DEFAULT NULL,
  T_VILLE nvarchar(35) DEFAULT NULL,
  T_PAYS nchar(3) DEFAULT NULL,
  T_TELEPHONE nvarchar(25) DEFAULT NULL,
  T_TELEX nvarchar(25) DEFAULT NULL,
  T_FAX nvarchar(25) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (T_TIERS,T_NATUREAUXI,ZONE),
  UNIQUE KEY T_AUXILIAIRE (T_AUXILIAIRE)
);

CREATE TABLE TRADDATA (
  TDA_CLE nvarchar(250) NOT NULL,
  TDA_CHAMP nvarchar(35) NOT NULL,
  TDA_LANG nvarchar(3) NOT NULL,
  TDA_VAL nvarchar(255) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (TDA_CLE,TDA_CHAMP,TDA_LANG,ZONE)
);

CREATE TABLE UTILISAT (
  US_UTILISATEUR nchar(3) NOT NULL,
  US_LIBELLE nvarchar(35) DEFAULT NULL,
  US_GROUPE nchar(3) DEFAULT NULL,
  US_ABREGE nvarchar(255) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (US_UTILISATEUR,ZONE)
);

CREATE TABLE UTILISATCOMPL (
  USC_UTILISATEUR nchar(3) NOT NULL,
  USC_ETABLISSEMENT nvarchar(6) DEFAULT NULL,
  USC_PRFCULTUREL nchar(3) DEFAULT NULL,
  USC_RESTR0 nchar(3) DEFAULT NULL,
  USC_RESTR5 nchar(3) DEFAULT NULL,
  USC_RESTR6 nchar(3) DEFAULT NULL,
  USC_DOMAINES nvarchar(255) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (USC_UTILISATEUR,ZONE)
);

CREATE TABLE YPRFCULTUREL (
  YPC_CODE nchar(3) NOT NULL,
  YPC_LANGPRINCDATA nchar(3) DEFAULT NULL,
  YPC_LANGSECONDATA nchar(3) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (YPC_CODE,ZONE)
);

CREATE TABLE YYLANGISO (
  YLG_CODEISOA2 nvarchar(3) NOT NULL,
  YLG_CODELANG nvarchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (YLG_CODELANG,ZONE)
);

CREATE TABLE YYLANGPAYSISO (
  YLN_ID nvarchar(7) NOT NULL,
  YLN_CODELANG nvarchar(3) NOT NULL,
  YLN_CODEMCD nvarchar(3) DEFAULT NULL,
  YLN_CODEPAYS nvarchar(3) NOT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (YLN_CODELANG,YLN_CODEPAYS,ZONE)
);

CREATE TABLE ZHERMES (
  ZHE_PARAMCODE nvarchar(20) NOT NULL,
  ZHE_PARAMLIBELLE nvarchar(1000) DEFAULT NULL,
  ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL,
  PRIMARY KEY (ZHE_PARAMCODE,ZONE)
);