ALTER TABLE ETABLISS
  MODIFY COLUMN ET_ADRESSE1 nvarchar(50) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_ADRESSE2 nvarchar(50) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_ADRESSE3 nvarchar(50) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_ADRESSE3 nvarchar(50) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_TELEPHONE nvarchar(25) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_VILLE nvarchar(35) DEFAULT NULL;

ALTER TABLE ETABLISS
    MODIFY COLUMN ET_CODEPOSTAL nvarchar(10) DEFAULT NULL;