ALTER TABLE TIERS ADD T_ETABLISSEMENT nvarchar(6) DEFAULT NULL AFTER T_PASSEPORT;
ALTER TABLE TIERS MODIFY ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL AFTER T_ETABLISSEMENT;

ALTER TABLE UTILISATCOMPL ADD USC_RESTR4 nchar(3) DEFAULT NULL AFTER USC_RESTR0;
ALTER TABLE UTILISATCOMPL MODIFY ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL AFTER USC_RESTR8;