ALTER TABLE DISPO DROP COLUMN GQ_DATEMODIF;

ALTER TABLE DISPO ADD GQ_DTSVLASTCHANGE datetime DEFAULT NULL AFTER GQ_RESERVETRF;
ALTER TABLE DISPO MODIFY ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP') NOT NULL AFTER GQ_DTSVLASTCHANGE;