
ALTER TABLE ARTICLE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER GA_LIBREART4;

ALTER TABLE ARTICLECOMPL MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE ARTICLETIERS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE CHOIXCOD MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE CHOIXEXT MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE COMMERCIAL MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER GCL_PRENOM;

ALTER TABLE COMMUN MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE DEPOTS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE DIMENSION MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE DISPO MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE DISPOSERIE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE ETABLISS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER ET_TYPEETAB;

ALTER TABLE LIGNE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE LIGNESERIE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE LINE_STATUS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE MARTICLETAB MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE METABDEPOT MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE MPOIDSNUMSERIE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE MTARIFCALC MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE OPERCAISSE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE PARCAISSE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE PIECE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER GP_STATUTPIECE;

ALTER TABLE PRINTING_QUEUE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER PRINTING_TYPE;

ALTER TABLE QUICKTRANSFER MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE REQUESTED_QUANTITY_BY_ARTICLE_FOR_CC MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE RESTRICTETAB MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE STATUS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE STKFICHETRACE MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE TIERS MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE TRADDATA MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE UTILISAT MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE UTILISATCOMPL MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE YPRFCULTUREL MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE YYLANGISO MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE YYLANGPAYSISO MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE ZHERMES MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE application_minimum_version MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE expiration_date MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE partitioned_exports MODIFY COLUMN cegid_area enum('EUR','ASS','AME','ASN','JAP', 'CHN') NOT NULL;

ALTER TABLE stock_groupe MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE stock_print_template MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE stock_store_printer MODIFY COLUMN ZONE enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL;

ALTER TABLE store_zone MODIFY COLUMN zone_id enum('WORLD','EUR','AME','ASN','ASS','JAP', 'CHN') NOT NULL AFTER web_store_id;